language: node_js
node_js:
  - '8'
  - '10'
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: lifeomic/dynamodb-dataloader
    node: '8'
